Roguelike-1 (Диздок)
shirokov-kirill/SD-roguelike pull request #1
Opened 2022-03-21 16:17 UTC by shirokov-kirill

2022-05-15 16:55 UTC, yurii-litvinov requested changes
Лучше связный текст со вставленными в него диаграммами, чтобы можно было читать единый документ. Ещё, кажется, совсем нет диаграмм последовательностей и состояний, которые просили в условии (соответственно, штраф к максимальному баллу). Объяснения причин принятия решений (rationale) тоже как-то нет, хотя это часть диздока.

2022-05-15 16:55 UTC, yurii-litvinov commented on README.md
> +6. Возможна поддержка сохранения игры
Это требования какие-то. В общи сведениях надо написать, что это за игра, в чём идея (ну, придумать какую-нибудь при необходимости), просто парой-тройкой предложений связного текста

2022-05-15 16:55 UTC, yurii-litvinov commented on README.md
> +## Ключевые требования
Стоило бы разделить их на бизнес-требования, функциональные и нефункциональные. И я бы ещё выделил в ключевые требования на симуляцию времени — пошаговая игра или реального времени.

2022-05-15 16:55 UTC, yurii-litvinov commented on README.md
> +2. Разработчик
Пользователь — не роль :) А ещё просили описание типичного пользователя.

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +# Описание Component Diagram
- Предоставляемые и потребляемые интерфейсы вызывают сомнения. Судя по диаграмме, Controller предоставляет интерфейс безымянному компоненту, тогда как по смыслу он контроллер, он, наверное, должен его вызывать, а не наоборот.
- Самый большой компонент на диаграмме без имени, судя по тексту это модель.
- Пунктирные стрелки нестандартные и непонятно, что такое. Судя по всему, они пытаются показать направленность потоков данных, но диаграмма компонентов структурная, поэтому так не умеет.
- Непунктирные стрелки тоже неканоничны, это должны были быть просто линии.

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +3. В дальнейшем Controller реализует весь жизненный цикл приложения (получение пользовательского ввода, интерпретация, уведомление онеобходимости изменения состояния приложения через State Modificati
```suggestion
3. В дальнейшем Controller реализует весь жизненный цикл приложения (получение пользовательского ввода, интерпретация, уведомление о необходимости изменения состояния приложения через State Modification Handler, реализация перерисовки в компоненте View через callback, дополнительные технические функции)
```

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +1. Class Controller содержит в себе состояние программы на уровне администрирования (начата ли игра, достигнута ли победа, открыты ли диалоговые окна и тд)
Судя по диаграмме, он статический (на самом деле, статические классы рисуются подчёркнутыми, без "static"), и кажется, что он один на всю игру, так что ничто не может пойти не так. Но писать юнит-тесты для такой системы может быть очень болезненно из-за невозможности замокать Controller. И вообще, статический класс с мутабельным состоянием — это просто законспирированная глобальная переменная, так что не очень.

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +# Описание Main Class Diagram
- FragmentsPool — это узел с диаграммы развёртывания, что довольно неожиданно на диаграмме классов, и, кажется, используется не по делу.
- Типы возвращаемых значений Type выглядят очень подозрительно
- Game я бы отобразил и на этой диаграмме (без полей и методов, потому что полное его определение — на отдельной диаграмме), и визуализировал бы связи с ним.
- Методы с многоточиями в именах в архитектуре не очень, намекают на неполную проработанность.
- Для enum-ов модификаторы видимости не указываются, да и рисуются по стандарту они не как у вас

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +5. В самом начале игры запускается Initializer, который генерирует начальное состояние приложения с помощью фабрики GameWorldBuilder и передаёт его в Controller для дальнейшей работы.
GameWorldBuilder, судя по всему, строитель, а не фабрика

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +2. GameWorld хранит в себе движок. При желании обновиться, GameWorld не делает это самостоятельно, а вызывается движок, который делает всё за него. В любой игре состояние может изменяться лишь под де
Можно было на диаграмме ассоциацию между GameEngine и GameWorld визуализировать. Или вас круговая зависимость испугала?

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +# Описание Game Class Diagram
Cнизу диаграммы — объекты? Если да, то плохая идея их на одной диаграмме с классами рисовать. Лучше сделать отдельную диаграмму объектов рядом. А ещё представлять Monster как экземпляр Creature, а конкретного монстра — как экземпляр Monster, неизбежно вынудит вас запутаться в метауровнях. И объекты со строчной пишутся :)

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +# Описание Game Class Diagram
То же с Response. Pass, судя по диаграмме — экземпляр Response, но Response — интерфейс, поэтому не может иметь экземпляров.

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +# Описание Game Class Diagram
Кстати, текстовое описание не делает этот момент понятнее, поэтому не годится :) Тут вообще используется довольно нетривиальная схема с атрибутами, поведениями и фасетами, про которую в архитектуре буквально ни слова.

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +# Описание ABF (Attributes-Behaviors-Facets) Class Diagram
Тут тоже внезапные узлы с диаграммы активностей, которые вы, видимо используете в значении "много разных классов". Лучше прямо классы нарисовать, архитектура же.

А ещё Extends над стрелками не пишется, и, кстати, реализация интерфейса в отличие от генерализации рисуется пунктирной стрелкой.

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +1. Attributes отвечают за характеристики существ в игре (здоровье/урон/уровень/внешность/позицию/инвентарь и тд). Они определяются для определённых типов сущностей через typealias. Например, здоровье
Тут тоже какое-то метапрограммирование, кажется. Конструируете тип из атрибутов в рантайме. Если уже так реализовали, то ок, но кажется, что это сложнее, чем нужно.

2022-05-15 16:55 UTC, yurii-litvinov commented on description/textDescriptions.md
> +5. В самом начале игры запускается Initializer, который генерирует начальное состояние приложения с помощью фабрики GameWorldBuilder и передаёт его в Controller для дальнейшей работы.
И непонятно, поддерживает ли он генерацию карты, и если не он, то кто?

2022-05-17 20:56 UTC, shirokov-kirill commented on README.md
> +6. Возможна поддержка сохранения игры
Fixed

2022-05-17 21:01 UTC, shirokov-kirill commented on README.md
> +## Ключевые требования
Fixed

2022-05-17 21:02 UTC, shirokov-kirill commented on README.md
> +2. Разработчик
Fixed

2022-05-17 21:09 UTC, shirokov-kirill commented on description/textDescriptions.md
> +1. Attributes отвечают за характеристики существ в игре (здоровье/урон/уровень/внешность/позицию/инвентарь и тд). Они определяются для определённых типов сущностей через typealias. Например, здоровье
Я определяю обращения к определённым полям объекта через Typealias, а конструирую с соответствующими атрибутами в EntityBuilder (да, важно передать все необходимые атрибуты в EntityBuilder, но поведение этих атрибутов может быть различно и определяется с помощью behavior и facet объекта)

2022-05-18 12:56 UTC, shirokov-kirill commented on description/textDescriptions.md
> +# Описание Component Diagram
Fixed

2022-05-18 13:34 UTC, shirokov-kirill commented on description/textDescriptions.md
> +1. Class Controller содержит в себе состояние программы на уровне администрирования (начата ли игра, достигнута ли победа, открыты ли диалоговые окна и тд)
Fixed

2022-05-18 14:27 UTC, shirokov-kirill commented on description/textDescriptions.md
> +# Описание Main Class Diagram
Fixed

2022-05-18 14:40 UTC, shirokov-kirill commented on description/textDescriptions.md
> +5. В самом начале игры запускается Initializer, который генерирует начальное состояние приложения с помощью фабрики GameWorldBuilder и передаёт его в Controller для дальнейшей работы.
Да, GameWorldBuilder -- строитель. Он возвращает сгенерированные данные. Алгоритм такой: мы его настраиваем и передаём данные (в том числе и фабрики сущностей, реализованные как "абстрактная фабрика"). Затем при вызове build() происходит генерация карты, а также генерация монстров на карте через фабрики.
То есть "абстрактные фабрики" передаются в "строитель", который уже их  совмещает

2022-05-18 15:02 UTC, shirokov-kirill commented on description/textDescriptions.md
> +5. В самом начале игры запускается Initializer, который генерирует начальное состояние приложения с помощью фабрики GameWorldBuilder и передаёт его в Controller для дальнейшей работы.
Fixed

2022-05-18 15:05 UTC, shirokov-kirill commented on description/textDescriptions.md
> +2. GameWorld хранит в себе движок. При желании обновиться, GameWorld не делает это самостоятельно, а вызывается движок, который делает всё за него. В любой игре состояние может изменяться лишь под де
Fixed

2022-05-18 15:25 UTC, shirokov-kirill commented on description/textDescriptions.md
> +# Описание Game Class Diagram
Да, там объекты. Я решил написать их здесь, так как они используются в программе для обозначения, своего рода, классовой принадлежности. (на фабриках сущностей, а также по ним могу определять принадлежность объекта к классу в дальнейшем).
Про Response я не совсем понимаю -- это две реализации интерфейса (файл app/src/main/kotlin/controller/messages/MessageResponse.kt) Пока что обозначил как реализацию.
Текстовое описание обновил

2022-05-18 19:33 UTC, shirokov-kirill commented on description/textDescriptions.md
> +# Описание ABF (Attributes-Behaviors-Facets) Class Diagram
Fixed

2022-06-14 09:15 UTC, yurii-litvinov requested changes

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +Уставший после работы или тяжелого дня человек, геймер
Геймер пойдёт в Elden Ring играть, например. Задача описания типичного пользователя в том, чтобы иметь в виду конкретного человека, который был бы реально заинтересован в вашем продукте. А не делать что-то для абстрактного геймера в вакууме, и получить продукт, который может быть хорошо сделан, но никому не нужен. Должны были учить на Software Engineering-е. Я помню, там ещё часто приводится пример типа телеграм-ботов для бабушек, которые подсказывают про пенсии и лекарство — и всё хорошо, только бабушки в большинстве своём не пользуются Telegram. Тут, например, это мог бы быть линуксовый админ Вася, который в детстве играл в Ангбанд и хочет играть на слабом компе прямо на работе, пока нечего делать, и не сильно палиться (поэтому консольная графика).

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +4. Viewer использует набор экранов, созданных с помощью библиотеки Zircon, применяя тот или иной в зависимости от команды пришедшей из Controller.
```suggestion
4. Viewer использует набор экранов, созданных с помощью библиотеки Zircon, применяя тот или иной в зависимости от команды, пришедшей из Controller.
```

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +3. StateModificationsHandler в данной ситуации не играет значительной роли, но полезен будет для (возможно) логирования действий, удобен для работы с несколькими состояниями (если такое потребуется),
Я за то, чтобы писать нужный код по мере появления нужды, а не делать абстракции "на будущее", которые надо сопровождать уже сейчас.

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +![MainClass](description/MainClassDiagram.png)
- "etc" на UML-диаграммах не пишут. Если не хотите рисовать какие-нибудь методы, просто не рисуете их, и всё.
- "Unit" тоже не пишут, это привязка к языку реализации. Просто не указывается тип возвращаемого значения.
- enumeration-ы рисуются сплошной линией, а не пунктирной.

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +![GameClass](description/GameClassDiagram.png)
Наверное, надо какой-то заголовок раздела, а то просто диаграмма посреди текста. По синтаксису тут, пожалуй, только одно замечание, `?` в UML пишется как `[0..1]`. Ну и по оформлению, не стоит выписывать детально все параметры с типами — можно либо имена параметров только писать, либо только типы. То, что position имеет тип Position3D, хорошо, но неинформативно (по крайней мере, не настолько, чтобы оправдать занимаемое место).

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +4. Effects - это дополнительные атрибуты с ограниченным периодом действия. Они могут влиять на поведение персонажа (Behavior), или же на другие аттрибуты (не представлено в данном приложении)
Круто, но неподробно. В заданиях 2-4 была куча архитектурных требований, для которых естественно было бы ожидать увидеть в архитектурной документации их реализацию. На диаграмме есть какие-то намёки, но паттерн "Состояние" я не увидел, паттерны "Стратегия" и "Декоратор" именно что как намёки, даже про "Прототип" непонятно, кто кого как и когда клонит.

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +![State](description/StateDiagram.png)
Состояние на диаграмме автоматов суть стабильное состояние системы, в котором она находится неопределённо долгое время и может из него выйти только по наступлению какого-то внешнего события. То, что у вас две стрелки без триггеров и одна стрелка не с триггером, а с forEach,, как бы намекает, что состояния "Modify..." — это не состояния, а действия по переходу. Настоящее состояние у вас только "Stay" (хотя по идее есть же автомат переходов между экранами, автомат состояний моба и т.п., что-то из этого можно было проиллюстрировать на диаграмме).

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +![Order](description/OrderDiagram.png)
`event + info` UML не умеет, над стрелкой пишется вызов метода. А ещё у вас линии активации начинаются до вызова метода, словно объекты уже работают, и их дёргают асинхронно (что противоречит самой же диаграмме потому что чёрный треугольник на конце стрелки обозначает синхронный вызов).

2022-06-14 09:15 UTC, yurii-litvinov commented on README.md
> +Идея про ABF довольно очевидна. В любой игре у персонажа есть атрибуты, и я их выделил в отдельную категорию. Атрибуты являются уникальными для каждого персонажа, и это отличает данныю группу от Beha
Не совсем правильно писать "я" про групповую работу (да и вообще в технической документации и научных текстах личные местоимения не используются). Лучше пассивный залог, не "я выделил", а "были выделены".

2024-01-01 16:52 UTC, merged