Final Roguelike
shirokov-kirill/SD-roguelike pull request #4
Opened 2022-05-18 13:57 UTC by shirokov-kirill

2022-06-14 10:47 UTC, yurii-litvinov requested changes
Документацию следует в этот же пуллреквест подмерджить, чтобы она эволющионировала вместе с кодом.

И тестовое покрытие как-то не очень.

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/GameConfig.kt
> +object GameConfig {
```suggestion
/**
  * Here are implemented all base
  * constants for game setup
  */
object GameConfig {
```
И ниже, надо комментарии оформить в формат KDoc

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/Controller.kt
> +class Controller {
Классам тоже нужны комментарии, даже больше, чем методам

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/Controller.kt
> +    companion object {
Паттерн "Одиночка" со своим состоянием не по делу лучше не применять, это осложняет тестирование, расширяемость и т.д., рассказывали на паре вроде

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/Controller.kt
> +            when (input) {
Смысл паттерна "Команда" как раз в том, чтобы такого не было. Команды сами могут содержать бизнес-логику, иметь Receiver (относительно которого выполняется действие) и иметь общий интерфейс с методом execute(), так что контроллеру останется только вызвать execute(). Это по идее более масштабируемо, и позитивно повлияет на баллы, потому что просили именно паттерн "Команда", а не просто обработчик событий.

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/Controller.kt
> +package controller
Имена пакетов неканоничныЪ. В JVM-языках используется стандартная нотация с "инвертированными" URL для поддержания глобальной уникальности имён пакетов.

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/messages/Clone.kt
> +data class Clone(
Напомню, что каждому классу надо комментарии

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/world/generator/GameWorldBuilder.kt
> +    fun passLoadingType(type: String): GameWorldBuilder {
Оно обычно set-что-нибудь или with-что-нибудь

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/world/generator/GameWorldBuilder.kt
> +            throw IllegalArgumentException("Not supported string passed")
А почему тогда не enum?

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/world/generator/GameWorldBuilder.kt
> +        if (loadingType == GENERATE) {
Это code smell "недоиспользованный полиморфизм". Тут фактически два класса в одном, и в каждом методе диспетчеризация выполняется вручную по тэгу типа loadingType. Очень нездоровая тема. Распилите на два класса с общим интерфейсом, станет лучше.

И я не буду задавать неудобные вопросы, типа "при загрузке из файла как используются размеры карты, переданные в конструктор билдера" :)

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/world/generator/GameWorldBuilder.kt
> +            while (equipmentCount > 0) {
```suggestion
            var equipmentCount = 15

            while (equipmentCount > 0) {
```

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/world/generator/GameWorldBuilder.kt
> +        }
```suggestion
        } 
```

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/world/generator/PositionExtensions.kt
> +    }.minus(this).shuffled()                                    // 4
Что за странные комментарии?

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/model/entity/attributes/effects/Cloneable.kt
> +    var actual = 0
Кстати, в Котлине же видимость по умолчанию public?

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/model/entity/behaviors/BaseBehavior.kt
> +                    if (effect is Cloneable) {
А вот тут бы switch как раз. Если действие эффекта не хотите переместить в сам эффект, конечно.

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/model/entity/behaviors/InputHandler.kt
> +                KeyCode.KEY_W -> {
Это класс в model, что намекает, что он не должен зависеть от "способа доставки" внешних сигналов, а тут прямо клавиша написана. Идеологически нехорошо.

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/test/kotlin/controller/InitializerTests.kt
> +//        Initializer.initialize(GameWorldBuilder.LOAD, "", Difficulty.EASY)
:(

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/test/kotlin/controller/messages/MessageResponseTest.kt
> +}
Не думаю, что этот тест помог вам найти много багов

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/controller/world/generator/GameWorldBuilder.kt
> +        if (loadingType == GENERATE) {
Да, и загрузку файла всё-таки просили в условии.

2022-06-14 10:47 UTC, yurii-litvinov commented on app/src/main/kotlin/model/entity/behaviors/BaseBehavior.kt
> +                if (effect is Embarrassment) {
Я бы сказал, что это не совсем декоратор. Даже совсем не декоратор. Если я не прав, поясните.

2022-06-27 19:43 UTC, vavilovm commented on app/src/test/kotlin/controller/InitializerTests.kt
> +//        Initializer.initialize(GameWorldBuilder.LOAD, "", Difficulty.EASY)
добавил загрузку карты из файлов

2024-01-01 17:00 UTC, merged